---
name: Build game

on: push

jobs:
  build-msvc:
    name: Windows build
    runs-on: windows-latest
    env:
      DXSDK_DIR: C:\apps\Microsoft DirectX SDK
      CONAN_PATH: C:\Program Files\Conan\conan\
    steps:
      - run: echo $env:CONAN_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v2.3.4

      - name: Install Microsoft DirectX SDK
        shell: cmake -P {0}
        run: |
          file(MAKE_DIRECTORY $ENV{DXSDK_DIR})
          file(DOWNLOAD https://vps.anotherfoxguy.com/ipfs/QmZm8WtxLxpmgxmYDTMPYjsbwmipr3KtrkPgGJoYiGBqhx "$ENV{TMP}/dl.zip" SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "$ENV{TMP}/dl.zip" WORKING_DIRECTORY "$ENV{DXSDK_DIR}")

      - name: Cache conan
        uses: actions/cache@v1
        with:
          key: conan-root-${{ hashFiles('**/hash.txt') }}
          path: ~/.conan

      - name: Cache conan packages
        uses: actions/cache@v1
        with:
          key: conan-pkg-${{ hashFiles('**/hash.txt') }}
          path: C:/.conan/

      - name: Install build dependencies
        run: choco install conan jom -y

      - name: Configure
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          cmake -G"NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=Release -DBUILD_REDIST_FOLDER=ON -DFETCHCONTENT_QUIET=OFF -DRUN_PMM=ON .
        shell: cmd

      - name: Create redis folder
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          jom package
        shell: cmd

      - name: Upload redist folder
        uses: actions/upload-artifact@v2
        with:
          name: ror-win
          path: Rigs of Rods-2021.2.zip

      - name: Clean Conan pkgs
        run: cmake -P ./pmm.cmake /Conan /Clean
        shell: cmd
